export enum BlockType {
    Start = 'start',
    Fly = 'fly',
    Turn = 'turn',
    Shoot = 'shoot',
    Color = 'color',
    PositionValue = 'position_value',
    Tile = 'tile',
    Position = 'position',
    Repeat = 'repeat',
    While = 'while',
    If = 'if',
    IfElse = 'if-else',
    SetVariable = 'setVariable',
    GetStringVariable = 'getStringVariable',
    GetNumericNumber = 'getNumericVariable',
    NumericCompare = 'numericCompare',
    StringCompare = 'stringCompare',
    LogicBinariOperation = 'logic_binary',
    LogicNot = 'logic_not',
    ConstantBoolean = 'constant_boolean',
    ConstantNumber = 'constant_number',
    ConstantString = 'constant_string',
}
