export enum StatementType {
    While = 'while',
    Repeat = 'repeat',
    If = 'if',
    Else = 'else',
    Start = 'start',
    Fly = 'fly',
    Shoot = 'shoot',
    PickUpDiamond = 'pick_up_diamond',
    Left = 'left',
    Right = 'right',
    TurnRight = 'turn-right',
    TurnLeft = 'turn-left',
    SetVariable = 'setVariable',
    SetVariableNumeric = 'setVariableNumeric',
    GetStringVariable = 'getStringVariable',
    GetNumericVariable = 'getNumericVariable',
    ConstantNumber = 'constant_number',
    ConstantString = 'constant_string',
    NumberBinary = 'number_binary',
    FunctionDefinition = 'function_definition',
    FunctionCallVoid = 'function_call_void',
    FunctionCallString = 'function_call_string',
    FunctionCallNumber = 'function_call_number',
}
