export enum StatementType {
    While = 'while',
    Repeat = 'repeat',
    If = 'if',
    Else = 'else',
    Start = 'start',
    Fly = 'fly',
    Shoot = 'shoot',
    Left = 'left',
    Right = 'right',
    TurnRight = 'turn-right',
    TurnLeft = 'turn-left',
    SetVariable = 'setVariable',
    GetStringVariable = 'getStringVariable',
    GetNumericVariable = 'getNumericVariable',
}
